services:
  app:
    build:
      context: ..      # This goes up one level to the root and Look for go.mod/pkg in the root
      dockerfile: hack/Dockerfile
    ports:
      - "8080:${PORT:-8080}"
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/clipdb?sslmode=disable
      - REDIS_URL=redis:6379
      - PORT=${PORT:-8080}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=clipdb
    volumes:
      # This line maps your local SQL file to the Docker auto-run folder
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
